# Thalloo Starter Template
#
# This project uses Jekyll to integrate with GitHub Pages.
# Configure the basic settings below to configure your copy.

# Your site settings
title: Environmental Evidence Maps
description: > # this means to ignore newlines until "baseurl:"
  Evidence-based maps and systematic maps produced by Oxford Systematic Reviews LLP.
baseurl: "/evidencemaps" # the subpath of your site, e.g. /blog
url: "https://oxsrev.github.io" # the base hostname & protocol for your site
ownername: "Oxford Systematic Reviews LLP"
ownerurl: "https://www.oxsrev.org"

# Internal configuration
plugins:
  - jekyll-remote-theme
remote_theme: AndrewIOM/thalloo
markdown: kramdown
collections:
  maps:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"